# Generated by Django 4.0.2 on 2022-03-11 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_petphoto_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
